"""add processing started time

Revision ID: 3457e77f163e
Revises: bc2cc0382959
Create Date: 2026-09-06 08:45:15.066041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3457e77f163e'
down_revision: Union[str, Sequence[str], None] = 'bc2cc0382959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_ups', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_ups', 'processing_started_at')
    # ### end Alembic commands ###
