"""add users table

Revision ID: 65d4ba9df729
Revises: d3df4dfd0e4e
Create Date: 2026-09-08 17:07:18.374671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d4ba9df729'
down_revision: Union[str, Sequence[str], None] = 'd3df4dfd0e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "clients",
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
    )

    op.create_index(
        "ix_clients_user_id",
        "clients",
        ["user_id"],
        unique=False,
    )

    op.create_foreign_key(
        "fk_clients_user_id_users",
        "clients",
        "users",
        ["user_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
