"""add follow up execution history

Revision ID: b7bd1075a898
Revises: b533e87b3db3
Create Date: 2026-09-06 10:41:14.739756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bd1075a898'
down_revision: Union[str, Sequence[str], None] = 'b533e87b3db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follow_up_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_ups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_executions_follow_up_id'), 'follow_up_executions', ['follow_up_id'], unique=False)
    op.create_index(op.f('ix_follow_up_executions_id'), 'follow_up_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_up_executions_id'), table_name='follow_up_executions')
    op.drop_index(op.f('ix_follow_up_executions_follow_up_id'), table_name='follow_up_executions')
    op.drop_table('follow_up_executions')
    # ### end Alembic commands ###
