"""add follow up retry fields

Revision ID: bc2cc0382959
Revises: d9e242cf07c7
Create Date: 2026-09-06 08:07:33.198002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2cc0382959'
down_revision: Union[str, Sequence[str], None] = 'd9e242cf07c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_ups', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('follow_ups', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('follow_ups', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_ups', 'next_retry_at')
    op.drop_column('follow_ups', 'last_error')
    op.drop_column('follow_ups', 'max_attempts')
    # ### end Alembic commands ###
