"""add email content to follow up executions

Revision ID: d3df4dfd0e4e
Revises: b7bd1075a898
Create Date: 2026-09-08 13:00:22.885621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3df4dfd0e4e'
down_revision: Union[str, Sequence[str], None] = 'b7bd1075a898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_up_executions', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('follow_up_executions', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_up_executions', 'body')
    op.drop_column('follow_up_executions', 'subject')
    # ### end Alembic commands ###
